# Generated by Django 3.1.5 on 2021-02-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210209_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
    ]
